import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { IoMdSunny, IoPartlySunnySharp } from "react-icons/io5";

export default function Home() {
  return (
    <>
      <Head>
        <title>Avinash Rao | Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <section className={styles.bgBlack}>
          <nav className='p-10 mb-12 flex justify-between'>
            <h1 className='text-xl'>Avinash Rao</h1>
            <ul className='flex row-auto items-center'>
              <li>
                <a
                  className='text-xl text-white hover:text-gray-300'
                  href='https://docs.google.com/document/d/1P-VQ-cWAOPuug_vvYbLwrKTmzR2D8ZW1hh-66WACEO4/edit?usp=sharing'
                  target='_blank'
                  rel='noopener noreferrer'>
                  Resume
                </a>
              </li>
              <li className='ml-10'>
                <a
                  className='text-xl text-white hover:text-gray-300'
                  href='https://github.com/avinash7rao'
                  target='_blank'
                  rel='noopener noreferrer'>
                  Github
                </a>
              </li>
              <li>
                {/* {DarkMode ? <IoMdSunny /> : <IoPartlySunnySharp />} */}
              </li>
            </ul>
          </nav>
        </section>
      </main>
    </>
  );
}
