import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { IoSunny, IoPartlySunnySharp } from "react-icons/io5";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import { BiUserCircle } from "react-icons/bi";
import myAvatar from "@/public/images/my-avatar.png";
import React, { createContext, useState } from "react";
import { IoDocumentTextOutline } from "react-icons/io5";
import EmailLink from "@/components/_atoms/EmailLink";
import { ImYoutube } from "react-icons/im";

type ThemeContextType = {
  darkMode: boolean;
  toggleTheme: () => void;
};

const ThemeContext = createContext<ThemeContextType>({
  darkMode: false,
  toggleTheme: () => {},
});

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  const toggleTheme = () => {
    setDarkMode(!darkMode);
  };

  return (
    <>
      <Head>
        <title>Avinash Rao | Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <ThemeContext.Provider value={{ darkMode, toggleTheme }}>
        <main className={darkMode ? "bg-gray-800 p-4" : "p-4"}>
          <section className={styles.bgBlack}>
            <nav className='p-4 mb-4 flex justify-end'>
              <ul className='flex row-auto items-center space-x-3'>
                <li>
                  <a
                    href='https://docs.google.com/document/d/1P-VQ-cWAOPuug_vvYbLwrKTmzR2D8ZW1hh-66WACEO4/edit?usp=sharing'
                    target='_blank'
                    aria-label='Avinash`s resume'
                    title='Avinash`s resume'
                    rel='noopener noreferrer'>
                    <IoDocumentTextOutline className='text-2xl text-white cursor-pointer' />
                  </a>
                </li>
                <li>
                  {darkMode ? (
                    <IoPartlySunnySharp
                      className='text-2xl text-white cursor-pointer'
                      onClick={toggleTheme}
                      title='Enable Dark Mode'
                    />
                  ) : (
                    <IoSunny
                      className='text-2xl text-white cursor-pointer'
                      onClick={toggleTheme}
                      title='Enable Light Mode'
                    />
                  )}
                </li>
              </ul>
            </nav>
            <div className='text-center pb-10'>
              <div className='mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96'>
                <Image src={myAvatar} alt='Avinash`s avatar' />
              </div>
              <h2 className='text-5xl py-4 text-teal-600 font-medium dark:text-teal-400 md:text-6xl'>
                Avinash Rao
              </h2>
              <h3 className='text-2xl py-2 dark:text-white md:text-3xl'>
                Developer & Designer.
              </h3>
              <p className='text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto'>
                I am a full stack developer and designer. I love to build
                beautiful and functional websites and applications.
              </p>
              <div className='py-3 flex justify-center space-x-4'>
                <a
                  href='https://www.linkedin.com/in/avinash-k-rao/'
                  target='_blank'
                  aria-label='Avinash`s LinkedIn profile'
                  title='Avinash`s LinkedIn profile'
                  rel='noopener noreferrer'>
                  <AiFillLinkedin className='text-4xl text-teal-500 hover:text-teal-600 cursor-pointer' />
                </a>
                <a
                  href='https://github.com/avinash7rao'
                  target='_blank'
                  aria-label='Avinash`s GitHub profile'
                  title='Avinash`s GitHub profile'
                  rel='noopener noreferrer'>
                  <AiFillGithub className='text-4xl text-teal-500 hover:text-teal-600 cursor-pointer' />
                </a>
                <EmailLink emailAddress='avinash7rao@gmail.com' />
                <a
                  href='https://www.youtube.com/@machis3150'
                  target='_blank'
                  aria-label='Avinash`s YouTube Channel'
                  title='Avinash`s YouTube Channel'
                  rel='noopener noreferrer'>
                  <ImYoutube className='text-4xl text-teal-500 hover:text-teal-600 cursor-pointer' />
                </a>
              </div>
            </div>
          </section>
        </main>
      </ThemeContext.Provider>
    </>
  );
}
